name = "Kiselevka dark theme"
version = "0.0.3"
authors = ["Konstantin Tereschenkov <kdubrovsky@gmail.com>"]
description = "Kiselevka dark color scheme for Zed"
repository = "https://github.com/kdubrovsky/kiselevka-zed"
id = "kiselevka-dark-theme"
schema_version = 1
